apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: demo-app
description: Use case demo pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: demo practice
gke:
 cluster: projects/practice-379412/locations/us-central1-c/clusters/dev
---