apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/practice-379412/practice/demo:v1
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: helloworld
      chartPath: ./demo/demochart
      valuesFiles:
        - ./demo/demochart/values.yaml